#!/usr/bin/env python
"""
sets core.fileMode=false for git repos
mostly for Windows, particularly Cygwin
"""
from subprocess import call
#
from pygitutils.common import codepath

rdir = codepath()

print('setting fileMode=false for all directories under {}'.format(rdir))
dlist = [x for x in rdir.iterdir() if x.is_dir()]
for d in dlist:
    call(['git','config','core.filemode','false'], cwd=str(d))
