#!/usr/bin/env python
"""
report on git repos not on the expected branch e.g. 'master'
"""
import subprocess as S
#
from pygitutils.common import codepath

OK='master' #branch you expect your git repos to be on

rdir = codepath()

cmd=['git','rev-parse','--abbrev-ref','HEAD']

dlist = [x for x in rdir.iterdir() if x.is_dir()]

branch=[]
for d in dlist:
    try:
        ret = S.check_output(cmd,  cwd=str(d)).decode('utf8').rstrip() #stderr=S.DEVNULL,

        if not OK in ret:
            branch.append((d,ret))
    except S.CalledProcessError as e:
        pass

if branch:
    print(branch)
