#!/usr/bin/env python3

"""
To check your Git commits locally for:
* no trailing whitespace
* PEP8 (python only)
* mypy type hint (python only)

1. set Git to look for pre-commit hook by in Terminal:
    git config --global core.hooksPath ~/.git/hooks
2. put this script at ~/.git/hooks/pre-commit (no .py extension)

To override this on per-repo basis, in that particular repo do:
git config core.hooksPath .git/hooks
so that you can put local hooks in that repo, no longer using this global pre-commit

* https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
* https://www.scivision.dev/git-commit-precheck-pep8/
"""

from pathlib import Path
import shutil
import subprocess
import sys

try:
    import yaml
except ImportError:
    yaml = None
    print("yaml checks not available", file=sys.stderr)

if not (flake8 := shutil.which("flake8")):
    print("flake8 checks not available", file=sys.stderr)
if not (mypy := shutil.which("mypy")):
    print("mypy checks not available", file=sys.stderr)


def check_yaml(file: Path) -> None:
    if yaml is None:
        return
    try:
        yaml.safe_load(file.read_text())
    except Exception as e:
        raise SystemExit(f"problem in YaML file {file}  {e}")


# %% Python checking
stdout = subprocess.check_output(["git", "diff", "--staged", "--name-only"], text=True)


def check_staged(stdout: str) -> list[str]:
    plist = []
    for file in stdout.split("\n"):
        path = Path(file)
        if not path.is_file():
            continue
        if path.suffix == ".py":
            if "breakpoint(" in path.read_text():
                raise SystemExit(f"Remove breakpoint in {path} before commit")
            plist.append(str(path))
        elif path.suffix in {".yml", ".yaml"}:
            check_yaml(path)

    return plist


plist = check_staged(stdout)

if plist:
    if flake8:
        if subprocess.call([flake8] + plist):
            raise SystemExit("fix PEP8 issues before commit")

    if mypy:
        if subprocess.call([mypy] + plist):
            raise SystemExit("fix type hinting issues before commit")

# %% general checks
if subprocess.call(["git", "diff-index", "--check", "--cached", "HEAD", "--"]):
    raise SystemExit("Fix whitespace issues before commit")
